# Change these first
owner: changeset-io # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Changeset Application
    url: https://changeset.io
  - name: Changeset Documentation
    url: https://docs.changeset.io
status-website:
  cname: status.changeset.io
  logoUrl: https://i.postimg.cc/Y9mSPtP0/changeset.png
  name: Changeset.io
  theme: light
  introTitle: "**Changeset.io** is the pull request automation tool for world-class engineering teams."
  introMessage: This page shows the status of the various Changeset applications
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/changeset-io/community

